baseURL = "www.example.com"
languageCode = "en-us"
themesDir = "themes"
theme = "hugo-whisper-theme"


pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true


[[menu.main]]
name = "首页"
url = "/"
weight = 1


[[menu.main]]
name = "开发指南"
url = "/Docs/"
weight = 2


[[menu.main]]
name = "设计指南"
url = "/Docs/"
weight = 3






[params.logo]
    mobile = "/images/logo-mobile.svg"
    standard  = "/images/logo.svg"